use indexmap::IndexMap;
use safe_relative_path::srpath;
use smol_str::SmolStr;

use crate::{
    config::Config,
    config_files::{ConfigFilePath, ConfigFileSource, ConfigFiles},
    error::Error,
};
use std::fmt::Write as _;

#[derive(serde::Deserialize, Debug, Clone, PartialEq)]
pub(in super::super) struct StoredZshConfig {
    environment: IndexMap<SmolStr, SmolStr>,
    alias: IndexMap<SmolStr, SmolStr>,
}

impl StoredZshConfig {
    pub fn make_config_files(
        &self,
        config: &Config,
        config_files: &mut ConfigFiles,
    ) -> Result<(), Error> {
        let Self { environment, alias } = self;

        // ~/.zshenv — sourced for every shell invocation
        let mut zshenv = String::new();
        _ = writeln!(zshenv, "#\n# Zsh environment config generated by zenops\n#\n");

        if config.has_cargo_packages() {
            _ = writeln!(zshenv, ". \"$HOME/.cargo/env\"");
            zshenv.push('\n');
        }

        if !environment.is_empty() {
            for (name, value) in environment {
                _ = writeln!(zshenv, "export {name}={value}");
            }
            zshenv.push('\n');
        }

        if let Some(path) = config.path_variable() {
            _ = writeln!(zshenv, "export PATH={path}");
            zshenv.push('\n');
        }

        #[cfg(target_os = "macos")]
        if let Some(spec) = config.stored.packages.0.get("llvm")
            && spec.is_brew()
        {
            _ = writeln!(zshenv, "export LDFLAGS=-L/opt/homebrew/opt/llvm/lib");
            _ = writeln!(zshenv, "export CPPFLAGS=-L/opt/homebrew/opt/llvm/include");
            zshenv.push('\n');
        }

        config_files.add(
            ConfigFilePath::in_home(srpath!(".zshenv")),
            ConfigFileSource::Generated(zshenv),
        );

        // ~/.zprofile — sourced for login shells (macOS only: brew shellenv)
        #[cfg(target_os = "macos")]
        {
            let mut zprofile = String::new();
            _ = writeln!(zprofile, "#\n# Zsh login profile generated by zenops\n#\n");
            _ = writeln!(zprofile, "eval \"$(/opt/homebrew/bin/brew shellenv)\"");

            config_files.add(
                ConfigFilePath::in_home(srpath!(".zprofile")),
                ConfigFileSource::Generated(zprofile),
            );
        }

        // ~/.zshrc — sourced for interactive shells
        let mut zshrc = String::new();
        _ = writeln!(zshrc, "#\n# Zsh interactive config generated by zenops\n#\n");

        if !alias.is_empty() {
            for (name, value) in alias {
                _ = writeln!(zshrc, "alias {name}={value}");
            }
            zshrc.push('\n');
        }

        config_files.add(
            ConfigFilePath::in_home(srpath!(".zshrc")),
            ConfigFileSource::Generated(zshrc),
        );

        Ok(())
    }
}
