use indexmap::IndexMap;
use safe_relative_path::srpath;
use smol_str::SmolStr;

use crate::{
    config::Config,
    config_files::{ConfigFilePath, ConfigFileSource, ConfigFiles},
    error::Error,
};
use std::fmt::Write as _;

#[derive(serde::Deserialize, Debug, Clone, PartialEq)]
pub(in super::super) struct StoredZshConfig {
    environment: IndexMap<SmolStr, SmolStr>,
    alias: IndexMap<SmolStr, SmolStr>,
}

impl StoredZshConfig {
    pub fn make_config_files(
        &self,
        config: &Config,
        config_files: &mut ConfigFiles,
    ) -> Result<(), Error> {
        let Self { environment, alias } = self;
        let mut zsh_config = String::new();

        _ = writeln!(
            zsh_config,
            "#\n# Zsh config generated by zenops, should be sourced from .zshrc\n#\n"
        );

        #[cfg(target_os = "macos")]
        {
            _ = writeln!(zsh_config, "eval \"$(/opt/homebrew/bin/brew shellenv)\"");
            zsh_config.push('\n');
        }

        if !alias.is_empty() {
            for (name, value) in alias {
                _ = writeln!(zsh_config, "alias {name}={value}");
            }
            zsh_config.push('\n');
        }

        if !environment.is_empty() {
            for (name, value) in environment {
                _ = writeln!(zsh_config, "export {name}={value}");
            }
            zsh_config.push('\n');
        }

        if let Some(path) = config.path_variable() {
            _ = writeln!(zsh_config, "export PATH={path}");
            zsh_config.push('\n');
        }

        #[cfg(target_os = "macos")]
        if let Some(spec) = config.stored.packages.0.get("llvm")
            && spec.is_brew()
        {
            _ = writeln!(zsh_config, "export LDFLAGS=-L/opt/homebrew/opt/llvm/lib");
            _ = writeln!(
                zsh_config,
                "export CPPFLAGS=-L/opt/homebrew/opt/llvm/include"
            );
            zsh_config.push('\n');
        }

        config_files.add(
            ConfigFilePath::in_home(srpath!(".zenops_zshrc")),
            ConfigFileSource::Generated(zsh_config),
        );

        Ok(())
    }
}
